server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/article
    username: root
    password: 123465
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: river
      password: 123465
mybatis:
  configuration:
    map-underscore-to-camel-case: true
token:
  jwt:
    expire: 10000000000
    signing-key: river-token-jwt-t-76